// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlKH6eN9Z9syFGSoZqynUszIgTvTd4G-g',
    appId: '1:981757263719:web:6d2e7cba09a701f62c79c2',
    messagingSenderId: '981757263719',
    projectId: 'fitnessapp-5f45f',
    authDomain: 'fitnessapp-5f45f.firebaseapp.com',
    storageBucket: 'fitnessapp-5f45f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrSXwIFZAtMv8K3ObWKbwKPdlepfWsDTU',
    appId: '1:981757263719:android:5aab8bd402d6538c2c79c2',
    messagingSenderId: '981757263719',
    projectId: 'fitnessapp-5f45f',
    storageBucket: 'fitnessapp-5f45f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhDU2YDWSr7X-_GhtntbAp4ZyQKggZ_pc',
    appId: '1:981757263719:ios:02929189c8e622ed2c79c2',
    messagingSenderId: '981757263719',
    projectId: 'fitnessapp-5f45f',
    storageBucket: 'fitnessapp-5f45f.appspot.com',
    iosBundleId: 'com.example.captainshoaib',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhDU2YDWSr7X-_GhtntbAp4ZyQKggZ_pc',
    appId: '1:981757263719:ios:1f827fb43fa5838f2c79c2',
    messagingSenderId: '981757263719',
    projectId: 'fitnessapp-5f45f',
    storageBucket: 'fitnessapp-5f45f.appspot.com',
    iosBundleId: 'com.example.captainshoaib.RunnerTests',
  );
}
